config/routes.rb
Rails.application.routes.draw do
  root 'calendars#index'
  resources :calendars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :plan, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    get_month
    get_week
    @plan = Plan.new
  end

  def create
    Plan.create(plan_params)
    redirect_to action: :index
  end

  private

  def plan_params
    params.require(:plan).permit(:date, :plan)
  end

  def get_month
    todays_year = Date.today.year
    todays_month = Date.today.month
    
    @first_day = Date.new(todays_year , todays_month , 1)
    @last_day = Date.new(todays_year , todays_month , -1)

    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']

    @month_days = []

    plans = Plan.where(date: @first_day..@last_day)

    # 下記 "last_month" をlmと表記する
    first_day_wday = @first_day.wday 
    if first_day_wday != 0
      first_day_wday.times do |x|
        lm_plans = []
        lm_wday_num = (@first_day - (first_day_wday - x)).wday
        lm_days = { date: (@first_day - (first_day_wday - x)).day, plans: lm_plans, wday: wdays[lm_wday_num] }
        @month_days.push(lm_days) 
      end
    end

    month_days = @last_day.day
    month_days.times do |x|
      today_plans = []
      plan = plans.map do |plan|
        today_plans.push(plan.plan) if plan.date == @first_day + x
      end
      wday_num = (@first_day+x).wday
      days = { date: (@first_day+x).day, plans: today_plans, wday: wdays[wday_num] }
      @month_days.push(days)
    end

  end

  def get_week
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']

    @todays_date = Date.today

    @week_days = []

    plans = Plan.where(date: @todays_date..@todays_date + 6)

    7.times do |x|
      today_plans = []
      plan = plans.map do |plan|
        today_plans.push(plan.plan) if plan.date == @todays_date + x
      end
      wday_num = (@todays_date+x).wday
      days = { month: (@todays_date + x).month, date: (@todays_date+x).day, plans: today_plans, wday: wdays[wday_num] }
      @week_days.push(days)
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_week.html.erb
<div class='calendar'>
  <% @week_days.each do |day| %>
    <div class='item'>
      <div class='date'>
        <%= day[:date] %>日
        <%if day[:wday] == "(土)" %>
          <span class='staday'><%= day[:wday] %></span>
        <%elsif day[:wday] == "(日)" %>
          <span class='sunday'><%= day[:wday] %></span>
        <%else %>
          <span><%= day[:wday] %></span>
        <% end %>
      </div>
      <ul class='content'>
        <% if day[:plans].length != 0 %>
          <% day[:plans].each do |plan| %>
            <li class='plan-list'>・<%= plan %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/calendars/index.html.erb
<div class='calendar-top'>
  <%= form_with model: @plan, url: calendars_path, class: 'form' do |f| %>
    <%= f.label :日付を選択, class: 'lavel' %>
    <%= f.date_field :date, class: 'date-select' %>
    <%= f.label :予定を入力, class: 'lavel' %>
    <%= f.text_field :plan, class: 'text-input' %>
    <%= f.submit '予定へ追加！', class: 'submit-btn' %>
  <% end %>

  <div class='month'>
    <span>
      <%= "#{@first_day.month}月の予定" %>
    </span>

  </div>

</div>

<div class = 'button'>
  <button type = "button" class = 'button_month_week' id = 'button_month_week'>月⇔今週</button>
</div>

<div class = 'week_plans' id = "week_plans" style = 'display: none;'>
  <%= render "week" %>
</div>

<div class='calendar' id='calendar'>
  <% @month_days.each do |day| %>
    <div class='item'>
      <div class='date'>
        <%= day[:date] %>日
        <%if day[:wday] == "(土)" %>
          <span class='staday'><%= day[:wday] %></span>
        <%elsif day[:wday] == "(日)" %>
          <span class='sunday'><%= day[:wday] %></span>
        <%else %>
          <span><%= day[:wday] %></span>
        <% end %>
      </div>
      <ul class='content'>
        <% if day[:plans].length != 0 %>
          <% day[:plans].each do |plan| %>
            <li class='plan-list'>・<%= plan %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>